---
- name: Install nncp
  ansible.builtin.package:
    name: nncp
    state: present
  tags:
    - role::nncp

- name: Create nncp configuration
  ansible.builtin.copy:
    content: "{{ nncp_configuration }}"
    dest: "{{ nncp_configuration_destination }}"
    owner: nncp
    group: nncp
    mode: 0400
  tags:
    - role::nncp
  notify:
    - Restart nncp-caller
    - Restart nncp-daemon

- name: Template nncp daemon unit
  ansible.builtin.template:
    src: nncp-daemon.service.j2
    dest: /etc/systemd/system/nncp-daemon.service
    owner: root
    group: root
    mode: "0444"
  register: nncp_daemon_unit
  notify:
    - Restart nncp-daemon
  when: nncp_daemon_enabled
  tags:
    - role::nncp

- name: Template nncp caller unit
  ansible.builtin.template:
    src: nncp-caller.service.j2
    dest: /etc/systemd/system/nncp-caller.service
    owner: root
    group: root
    mode: "0444"
  register: nncp_caller_unit
  notify:
    - Restart nncp-caller
  tags:
    - role::nncp

- name: Template nncp toss unit
  ansible.builtin.template:
    src: nncp-toss.service.j2
    dest: /etc/systemd/system/nncp-toss.service
    owner: root
    group: root
    mode: "0444"
  register: nncp_toss_unit
  notify:
    - Restart nncp-toss
  tags:
    - role::nncp

- name: Template nncp cleanup units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0444"
  register: nncp_clean_unit
  loop:
    - nncp-clean.service
    - nncp-clean.timer
  notify:
    - Restart nncp-clean
  tags:
    - role::nncp

- name: Template nncp reass units
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: "0444"
  register: nncp_reass_unit
  loop:
    - nncp-reass.service
    - nncp-reass.timer
  notify:
    - Restart nncp-reass
  tags:
    - role::nncp

- name: Copy logrotate configuration
  ansible.builtin.template:
    src: logrotate-nncp.j2
    dest: /etc/logrotate.d/nncp
    owner: root
    group: root
    mode: "0444"
  tags:
    - role::nncp

- name: Start and enable units
  ansible.builtin.service:
    daemon_reload: "{{ (nncp_clean_unit is changed) or (nncp_daemon_unit is changed) or (nncp_caller_unit is changed) or (nncp_toss_unit is changed) or (nncp_reass_unit is changed) }}"
    name: "{{ item }}"
    state: "{{ (item == 'nncp-daemon.service') | ternary('started', (nncp_daemon_enabled | ternary('started', 'stopped'))) }}"
    enabled: "{{ item != 'nncp-daemon.service' or nncp_daemon_enabled }}"
  loop:
    - nncp-caller.service
    - nncp-clean.timer
    - nncp-daemon.service
    - nncp-reass.timer
    - nncp-toss.service
  tags:
    - role::nncp
