---
- name: restart nncp-daemon
  service:
    name: nncp-daemon.service
    state: restarted
  tags:
    - role::nncp

- name: restart nncp-clean
  service:
    name: nncp-clean.timer
    state: restarted
  tags:
    - role::nncp

- name: restart nncp-reass
  service:
    name: nncp-reass.timer
    state: restarted
  tags:
    - role::nncp

- name: restart nncp-caller
  service:
    name: nncp-caller.service
    state: restarted
  tags:
    - role::nncp

- name: restart nncp-toss
  service:
    name: nncp-toss.service
    state: restarted
  tags:
    - role::nncp
